### ISSUE TITLE
App crashes no matter what hachimi.dll is re-named to after latest update.

### ISSUE THREAD

**Issue by lugerron** [Hachimi-Hachimi/Hachimi#38]
After the latest UMPD update, the Windows application crashes no matter what the hachimi.dll is renamed to.  I have tried both dxgi.dll and opengl32.dll with the same results.  Removing the dll allows the application to launch normally.

**Comment by KevinVG207** [comment]
It appears non-modded users had similar issues and the game update has been reverted on the DMM platform. 
https://umamusume.jp/news/detail?id=2226

**Comment by lugerron** [comment]
It does appear that way!  It's working again.
